[package]
name = "kirocode"
version = "0.0.1"
authors = ["yusei-wy <yusei.kasa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.1"
